export const langEN = {
  navhome: 'Home',
  navabout: 'About',
  navcontact: 'Contact',
  navkinematics: 'Kinematics',
  navMRU: 'Uniformly Motion Calculator',
  navMRUA: 'Uniformly Accelerated Motion Calculator',
  navdynamics: 'Dynamics',
  nav1stlaw: 'First Newton Law',
  nav2ndlaw: 'Second Newton Law',
  nav3rdlaw: 'Third Newton Law',
  homeh1: 'Physics',
  homespan: 'problem solver',
  homeparrafo1: 'In this app, you are going to solve your school physics problems!!',
  homeparrafo2: 'Please, use it only to check your solutions, if you want to learn you should try to solve the problems yourself before using this!',
  abouth1: 'About',
  abouth2: 'My name is Ingmar!!',
  page404h1: 'Page  Not Found',
  page404h2: 'This URL is not correct',
  mruh1: 'Uniformly Rectilinear Motion',
  mruh41: 'The Uniformly Rectilinear Motion , is one with constant speed and whose trajectory is a straight line. A clear example is the sliding doors of an elevator, they generally open and close in a straight line and always at the same speed. Below is a general formula and the variables that we find:',
  mruli1: 'So : Initial Position',
  mruli2: 'S : Position after T',
  mruli3: 'to : Initial time',
  mruli4: 't : Time elapsed',
  mruli5: 'Vo : Velocity (constant)',
  mruh42: 'Note that when we say that the velocity is constant we are saying that neither its value (also known as modulus, speed or celerity) nor the direction of movement changes.',
  mrusolver: 'Problem Solver',
  mruresultto: 'Initial time: ',
  mruresultt: 'Time elapsed: ',
  mruresults: 'Position: ',
  mruresultso: 'Initial position: ',
  mruresultvo: 'Velocity: ',
  mruselectproblem: 'Select problem type: ',
  mrufindto: ' Known S,So,Vo y t, find to ',
  mrufindt: ' Known S,So,Vo y to, find t ',
  mrufindvo: ' Known S,So,to y t, find Vo ',
  mrufindso: ' Known S,Vo,to y t find So ',
  mrufinds: ' Known So,Vo,to y t find S ',
  mruselectunits: 'Select problem units: ',
  mruunitms: ' Meters, seconds ',
  mruunitkmh: ' Kilometers, hour ',
  mruunitmph: ' Miles, hous',
  mruclear: 'Clear fields',
  mrucalc: 'Solve!',
}