export const langEN = {
  navhome: 'Home',
  navabout: 'About',
  navcontact: 'Contact',
  navkinematics: 'Kinematics',
  navMRU: 'Uniformly Motion Calculator',
  navMRUA: 'Uniformly Accelerated Motion Calculator',
  navdynamics: 'Dynamics',
  nav1stlaw: 'First Newton Law',
  nav2ndlaw: 'Second Newton Law',
  nav3rdlaw: 'Third Newton Law',
  homeh1: 'Physics',
  homespan: 'problem solver',
  homeparrafo1: 'In this app, you are going to solve your school physics problems!!',
  homeparrafo2: 'Please, use it only to check your solutions, if you want to learn you should try to solve the problems yourself before using this!',
  abouth1: 'About',
  abouth2: 'My name is Ingmar!!',
  page404h1: 'Page  Not Found',
  page404h2: 'This URL is not correct',
}