export const langES = {
  navhome: 'Inicia',
  navabout: 'Sobre mi',
  navcontact: 'Contacto',
  navkinematics: 'Cinematica',
  navMRU: 'Movimiento Rectilineo Uniforme',
  navMRUA: 'Movimiento Rectilineo Uniformemente Acelerado',
  navdynamics: 'Dinamica',
  nav1stlaw: 'Primera Ley de Newton',
  nav2ndlaw: 'Segunda Ley de Newton',
  nav3rdlaw: 'Tercera Ley de Newton',
  homeh1: 'Fisica:',
  homespan: 'Solucionador de problemas',
  homeparrafo1: 'Con esta App podras resolver los problemas de fisica.',
  homeparrafo2: 'Por favor, usalo solo para comprobar tus soluciones, si quieres aprender deberias intentar resolver los problemas por tu cuenta antes de usarme!',
  abouth1: 'Sobre mi:',
  abouth2: 'Mi nombre es Ingmar!!',
  page404h1: 'Pagina no encontrada',
  page404h2: 'Esta direccion URL no es correcta.',
}