export const langES = {
  navhome: 'Inicio',
  navabout: 'Sobre mi',
  navcontact: 'Contacto',
  navkinematics: 'Cinematica',
  navMRU: 'Movimiento Rectilineo Uniforme',
  navMRUA: 'Movimiento Rectilineo Uniformemente Acelerado',
  navdynamics: 'Dinamica',
  nav1stlaw: 'Primera Ley de Newton',
  nav2ndlaw: 'Segunda Ley de Newton',
  nav3rdlaw: 'Tercera Ley de Newton',
  homeh1: 'Fisica:',
  homespan: 'Solucionador de problemas',
  homeparrafo1: 'Con esta App podras resolver los problemas de fisica.',
  homeparrafo2: 'Por favor, usalo solo para comprobar tus soluciones, si quieres aprender deberias intentar resolver los problemas por tu cuenta antes de usarme!',
  abouth1: 'Sobre mi:',
  abouth2: 'Mi nombre es Ingmar!!',
  page404h1: 'Pagina no encontrada',
  page404h2: 'Esta direccion URL no es correcta.',
  mruh1: 'Movimiento Rectilineo uniforme',
  mruh41: 'El movimiento rectilíneo uniforme (m.r.u.), es aquel con velocidad constante y cuya trayectoria es una línea recta. Un ejemplo claro son las puertas correderas de un ascensor, generalmente se abren y cierran en línea recta y siempre a la misma velocidad. A continuacion se muestra formula general y las incognitas que encontramos:',
  mruli1: 'So : Posicion inicial',
  mruli2: 'S : Posicion transcurrido un tiempo T',
  mruli3: 'to : Instante inicial',
  mruli4: 't : Tiempo transcurrido',
  mruli5: 'Vo : Velocidad inicial (constante)',
  mruh42: 'Observa que cuando afirmamos que la velocidad es constante estamos afirmando que no cambia ni su valor (también conodido como módulo, rapidez o celeridad) ni la dirección del movimiento.',
  mrusolver: 'Solucionador de problemas',
  mruresultto: 'El valor del instante inicial es: ',
  mruresultt: 'El valor del tiempo transcurrido es: ',
  mruresults: 'La posicion sera: ',
  mruresultso: 'La posicion inicial ha sido: ',
  mruresultvo: 'La velocidad sera de: ',
  mruselectproblem: 'Seleccione el tipo de problema: ',
  mrufindto: ' Conocemos S,So,Vo y t, buscamos to ',
  mrufindt: ' Conocemos S,So,Vo y to, buscamos t ',
  mrufindvo: ' Conocemos S,So,to y t, buscamos Vo ',
  mrufindso: ' Conocemos S,Vo,to y t buscamos So ',
  mrufinds: ' Conocemos So,Vo,to y t buscamos S ',
  mruselectunits: 'Selecciona las unidades del problema: ',
  mruunitms: ' Metros, segundos ',
  mruunitkmh: ' Kilometros, horas ',
  mruunitmph: ' Millas, horas',
  mruclear: 'Limpiar datos',
  mrucalc: 'Calcular',

  
  



}